env:
  browser: true
  es2021: true
  jest: true

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - import

rules:
  no-unused-vars: error
  no-undef: error
  no-unreachable: error
  no-mixed-spaces-and-tabs: error
  no-console: off

  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - state
  import/no-extraneous-dependencies:
    - error
    - devDependencies: false
  import/extensions: 0
  import/no-unresolved: error
  import/prefer-default-export: off
  consistent-return: off
  no-shadow: off
  func-names: off
  no-use-before-define: off
  object-curly-newline: off
  max-len:
    - error
    - code: 120

  react/jsx-indent:
    - error
    - 2
  react/jsx-indent-props:
    - error
    - 2
  react/jsx-closing-bracket-location: error
  react/destructuring-assignment: error
  react/jsx-wrap-multilines: error
  react/prop-types: off

settings:
  react:
    version: detect
