env:
  browser: true
  es2021: true
  jest: true

parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - import
  - react

rules:
  no-console: off
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - state
  import/extensions: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies: false
  import/no-unresolved: error
  consistent-return: off
  no-use-before-define: off
  max-len:
    - error
    - code: 120
  react/prop-types: off
  react/jsx-indent:
    - error
    - 2
  react/jsx-indent-props:
    - error
    - 2
  react/jsx-closing-bracket-location: error
  react/destructuring-assignment: error
  react/jsx-wrap-multilines: error

settings:
  react:
    version: detect
