env:
  browser: true
  es2021: true
  jest: true

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - import

rules:
  no-param-reassign:
    - error
    - props: true
      ignorePropertyModificationsFor:
        - state
  no-console: off
  import/extensions: 0
  react/prop-types: off
  react/jsx-indent:
    - error
    - 2
  react/jsx-indent-props:
    - error
    - 2
